version: "3.8"

services:

  backend:
    build: ./backend
    container_name: node_api
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    networks:
      - app_network

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
